"""Markdown brief export for CommentPulse."""

import sqlite3
from datetime import datetime

from .db import get_themes, get_comments_by_theme, get_sources


def export_brief(conn: sqlite3.Connection, output_path: str = "weekly-brief.md") -> str:
    """Export a Markdown brief with themes, representative comments, and content ideas.

    Returns the path to the exported file.
    """
    themes = get_themes(conn)
    sources = get_sources(conn)
    source_names = {s["id"]: s["title"] for s in sources}

    lines = []
    now = datetime.now().strftime("%Y-%m-%d")

    lines.append(f"# CommentPulse Weekly Brief — {now}")
    lines.append("")
    lines.append(f"**Sources:** {len(sources)} | **Themes:** {len(themes)} | **Generated:** {datetime.now().isoformat()}")
    lines.append("")
    lines.append("---")
    lines.append("")

    if not themes:
        lines.append("No themes found. Run `commentpulse themes` first.")
        lines.append("")
    else:
        for i, theme in enumerate(themes, 1):
            lines.append(f"## Theme {i}: {theme['label']}")
            lines.append("")
            lines.append(f"**Category:** {theme['category']} | "
                        f"**Comments:** {theme['comment_count']} | "
                        f"**Confidence:** {theme.get('confidence', 0):.0%}")
            lines.append("")
            if theme.get("summary"):
                lines.append(f"*{theme['summary']}*")
                lines.append("")

            # Representative comments (up to 5)
            comments = get_comments_by_theme(conn, theme["id"])
            shown = min(5, len(comments))

            lines.append("### Evidence")
            lines.append("")

            for c in comments[:shown]:
                permalink = c.get("permalink") or ""
                author = c.get("author") or "anonymous"
                text = c["text"]

                # Truncate long comments
                if len(text) > 300:
                    text = text[:297] + "..."

                if permalink:
                    lines.append(f"- **{author}**: {text} [→]({permalink})")
                else:
                    lines.append(f"- **{author}**: {text}")

            if len(comments) > shown:
                lines.append(f"- *...and {len(comments) - shown} more*")

            lines.append("")

            # Content idea suggestion based on category
            idea = _content_idea(theme["category"], theme["label"])
            if idea:
                lines.append(f"### Content idea")
                lines.append(f"> {idea}")
                lines.append("")

            lines.append("---")
            lines.append("")

    # Footer
    lines.append("## Summary")
    lines.append("")

    category_counts = {}
    for t in themes:
        cat = t["category"]
        category_counts[cat] = category_counts.get(cat, 0) + t["comment_count"]

    if category_counts:
        lines.append("| Category | Comments |")
        lines.append("|---|---:|")
        for cat, count in sorted(category_counts.items(), key=lambda x: -x[1]):
            lines.append(f"| {cat} | {count} |")
        lines.append("")

    lines.append(f"*Generated by CommentPulse v0.1.0-alpha.1 on {now}*")
    lines.append("")

    content = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path


def _content_idea(category: str, label: str) -> str:
    """Generate a simple content idea suggestion based on theme category."""
    ideas = {
        "question": f"Create a tutorial or FAQ video addressing: {label}",
        "pain": f"Address this pain point directly: {label}. Show a solution or workaround.",
        "objection": f"Acknowledge this objection in your next video: {label}. Explain the tradeoff.",
        "praise": f"Highlight what's working: {label}. Double down on this in future content.",
        "urgent-support": f"Prioritize a fix or response video for: {label}. This is urgent.",
        "general": f"Explore this topic further: {label}",
    }
    return ideas.get(category, "")
